name: closure
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-learn
  - matplotlib-base
  - jupyterlab
  - ipywidgets
  - tqdm
  - pyqg
  - h5py
  - git
  - jax
  - flax
  - optax
  - jaxlib=*=*cuda*
