name: closure
channels:
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - cudatoolkit=11.4
  - numpy
  - scipy
  - matplotlib-base
  - jupyterlab
  - git
  - pip
  - pip:
    - '--find-links=https://storage.googleapis.com/jax-releases/jax_releases.html'
    - 'jax[cuda]'
    - 'flax'
    - 'optax'
